name = "flexile-web"
compatibility_date = "2024-09-23"
pages_build_output_dir = ".vercel/output/static"

[vars]
NEXT_PUBLIC_API_URL = "http://localhost:8787"

# ---------------------
# Staging Environment
# ---------------------
[env.staging]
name = "flexile-web-staging"

[env.staging.vars]
NEXT_PUBLIC_API_URL = "https://api-staging.flexile.com"

# ---------------------
# Production Environment
# ---------------------
[env.production]
name = "flexile-web"

[env.production.vars]
NEXT_PUBLIC_API_URL = "https://api.flexile.com"
